old:
  image: "${OLD_IMAGE}"
  volumes:
    - .:/.docker-image-diff/
  command: /.docker-image-diff/expose-filesystem-root.sh
  expose:
    - "873"
new_large_layer:
  image: "${NEW_IMAGE}"
  links:
   - old
  volumes:
    - .:/.docker-image-diff/
  environment:
    - RESTRICT_DIFF_TO_PATH=${RESTRICT_DIFF_TO_PATH}
  command: /.docker-image-diff/create-changelog-to-go-from-old-to-new.sh
